import React from "react";
import { db } from "../Services/firebase";
import {
  collection,
  doc,
  writeBatch,
  serverTimestamp,
  updateDoc,
} from "firebase/firestore";

// 🔹 Data barang baru
const items = [
  "sp 1",
  "sp 2",
  "sp 3",
  "sp 4",
  "sp 5",
  "sp 6",
  "sp 7",
  "sp 8",
  "sp 9",
  "sp 10",
  "sp 11",
  "sp 12",
  "sp 13",
  "sp 14",
  "sp 15",
  "sp 16",
  "sp 17",
  "sp 18",
  "sp 19",
  "sp 20",
  "sp 21",
  "sp 22",
  "sp 23",
  "sp 24",
  "sp 25",
  "sp 26",
  "sp 27",
  "sp 28",
  "sp 29",
  "sp 30",
  "sp 31",
  "sp 32",
  "sp 33",
  "sp 34",
  "sp 35",
  "sp 36",
  "sp 37",
  "sp 38",
  "sp 39",
  "sp 40",
  "sp 41",
  "sp 42",
  "sp 43",
  "sp 44",
  "sp 45",
  "sp 46",
  "sp 47",
  "sp 48",
  "sp 49",
  "sp 50",
  "sp 51",
  "sp 52",
  "sp 53",
  "sp 54",
  "sp 55",
  "sp 56",
  "sp 57",
  "sp 58",
  "sp 59",
  "sp 60",
  "sp 61",
  "sp 62",
  "sp 63",
  "sp 64",
  "sp 65",
  "sp 66",
  "sp 67",
  "sp 68",
  "sp 69",
  "sp 70",
  "sp 71",
  "sp 72",
  "sp 73",
  "sp 74",
  "sp 75",
  "sp 76",
  "sp 77",
  "sp 78",
  "sp 79",
  "sp 80",
  "sp 81",
  "sp 82",
  "sp 83",
  "sp 84",
  "sp 85",
  "talas A1",
  "mocca A3",
  "c polisi A4",
  "abu md A5",
  "dw B1",
  "coksu B2",
  "coklat sd B3",
  "coklat B4",
  "abu B5",
  "vario C1",
  "coksu sd C2",
  "van houten C3",
  "coklat C4",
  "ungu C5",
  "hijau md D1",
  "coklat md D3",
  "talas D4",
  "dongker D5",
  "toska sdg E1",
  "milo E3",
  "biru sdg F1",
  "abu md F2",
  "gold F3",
  "navy F4",
  "salem D3",
  "abu A1 B",
  "abu A2",
  "hijau spl",
  "kubus B1",
  "abu spl",
  "hj busuk 1",
  "hj busuk 2",
  "milo spl",
  "peach spl",
  "F2 tua",
  "sage shanon",
  "coklat shanon",
  "silver shanon",
  "lavender sm",
  "burgundy sm",
  "anggur sm",
  "maroon sm",
  "baby A sm",
  "hitam sm",
  "A1 K",
  "B1 K",
  "B2 K",
  "B3 K",
  "B4 K",
  "B5 K",
  "C2 K",
  "C3 K",
  "C4 K",
  "F4 K",
  "G4 K",
  "H2 K",
  "peach wm",
  "jingga wm",
  "rose md wm",
  "pemda wm",
  "susu pucet wm",
  "milo wm",
  "turkis sd wm",
  "kopi wm",
  "abu sd wm",
  "abu md wm",
  "susu B wm",
  "hijau TR wm",
  "magenta wm",
  "milk wm",
  "ma2 wm",
  "ma1 wm",
  "baby A wm",
  "hansip wm",
  "csd wm",
  "dw md wm",
  "pon wm",
  "khaky wm",
  "talas TL wm",
  "peach spl wm",
  "bata wm",
  "kubus wm",
  "H2K wm",
  "sp 51 wm",
  "B4 wm",
  "sp 37 wm",
  "caramel wm",
  "E1 wm",
  "F2 md wm",
  "talas A1 wm",
  "tab wm",
  "lavender wm",
  "BBB wm",
  "pon T wm",
  "putih wm",
  "B5 wm",
  "hitam wm",
  "BBA wm",
  "dongker wm",
  "abu A1 md wm",
  "m cabe ab",
  "maroon ab",
  "ungu lilac ab",
  "abu ab",
  "hijau sage ab",
  "cream 1306 ab",
  "cream 1022 ab",
  "hitam ab",
  "benhur ab",
  "kubus ab",
  "dongker ab",
  "emerald lc",
  "anggur lc",
  "kopi 55 lc",
  "pink rose lc",
  "lavender T lc",
  "melon 4212 lc",
  "hijau terang lc",
  "telor asin lc",
  "peach T lc",
  "coklat 1991 lc",
  "kubus lc",
  "plum lc",
  "kuning 662 lc",
  "maroon lc",
  "1600 lc",
  "toska sd lc",
  "155 lc",
  "toska T lc",
  "fanta lc",
  "ungu 986 lc",
  "TMT lc",
  "argentina lc",
  "burgundy lc",
  "toska mj",
  "ungu md mj",
  "navy bas",
  "emerald bas",
  "bw ab",
  "bw ow",
  "bw sm",
  "bw bas",
  "bw A1",
  "violet 986 lc",
  "melon 1362 lc",
];

// 🔸 Ganti karakter ilegal untuk Firestore doc ID
const sanitizeId = (str) => str.replace(/[.#$[\]]/g, "_").trim();

export default function DeleteItemFirestore() {
  const uploadData = async () => {
    const batch = writeBatch(db);
    const namaKategori = "HG60";

    // 📁 Semua dokumen akan disimpan di koleksi "produk"
    const baseCollection = collection(db, "barang");

    items.forEach((id) => {
      const docId = sanitizeId(id);
      const ref = doc(baseCollection, docId);
      batch.delete(ref);
    });

    // items.forEach((item) => {
    //   const docId = sanitizeId(item);
    //   const firestoreId =
    //     namaKategori.toUpperCase().split(" ").join("") +
    //     "-" +
    //     docId.toUpperCase().split(" ").join("");
    //   const docRef = doc(baseCollection, firestoreId);

    //   batch.set(
    //     docRef,
    //     {
    //       id: firestoreId,
    //       aktif: true,
    //       nama: item,
    //       kategori: namaKategori,
    //       stokEcer: 0,
    //       stokRol: 0,
    //       totalBerat: 0,
    //       harga: 0,
    //       updatedAt: serverTimestamp(),
    //     },
    //     { merge: false }
    //   );
    // });

    try {
      await batch.commit();
      alert(`✅ Bulk delete selesai!`);
    } catch (error) {
      console.error("❌ Error upload:", error);
    }
  };

  return (
    <div>
      <button
        onClick={uploadData}
        className="border rounded-md px-2 py-1 w-1/2 focus:ring-2 focus:ring-[#243A8C]"
      >
        Delete Item
      </button>
    </div>
  );
}
